"""Built-in example arts.

These are the same examples used by the test suite and the theory
documentation, plus the Invader that inspired the whole project, plus
a few arts **generated by a vision language model** (the ``vlm_*``
ones -- produced with the same prompt as :mod:`ascii3d.vlm`, then
turned with the engine).
"""

__all__ = ['EXAMPLES']

DOT = """\
 _
|_|
"""

CUBE = """\
 ______
| _  _ |
||_||_||
|______|
"""

HEAD = """\
 __________
|  __  __  |
| |  ||  | |
| |__||__| |
|          |
|__________|
"""

ROOMY = """\
 __________
|          |
|          |
|          |
|          |
|__________|
"""

RUBIK = """\
 __________
|   |  |   |
|   |  |   |
|   |  |   |
|   |  |   |
|___|__|___|
"""

INVADER = """\
     __
   _|  |_
 _|      |_
|  _    _  |
| |_|  |_| |
|  _    _  |  _
|_|_|_| |__| |_|_|_|
 |_|_        _|_|
   |_|      |_|
"""

# Generated by a vision language model (see ascii3d/vlm.py); the
# prompts are kept next to the names so the provenance is clear.
VLM_CAT = r"""         _
       _/ \_
     _/     \_
    /         \
   |  o     o  |
   |    \_/    |
   |     |     |
    \   / \   /
     \_/   \_/
      |     |
      |     |
      |_____|
"""

VLM_HOUSE = r"""      _______
     /       \
    /         \
   /   ___     \
  |   |   |     |
  |   |   |     |
  |   |___|     |
  |     | |     |
  |     | |     |
  |     |_|     |
  |      |      |
  |      |      |
  |      |      |
  |______|______|
"""

VLM_ROCKET = r"""     _
   _/ \_
  /     \
 |  o o  |
 |   |   |
 |  / \  |
 | /   \ |
 |/     \|
  \  |  /
   \ | /
    \|/
     +
    /|\
   / | \
  /  |  \
"""

VLM_ROBOT = r"""      ___
     /   \
    |  o  |
    |     |
    |  o  |
     \___/
       |
     _/ \_
    /     \
   |  ^  |
  /|     |\
 / |     | \
    \___/
   /     \
  /_______\
"""

EXAMPLES = {
    'dot': DOT,
    'cube': CUBE,
    'head': HEAD,
    'roomy': ROOMY,
    'rubik': RUBIK,
    'invader': INVADER,
    'vlm_cat': VLM_CAT,
    'vlm_house': VLM_HOUSE,
    'vlm_rocket': VLM_ROCKET,
    'vlm_robot': VLM_ROBOT,
}
