site_name: ASCII3D
nav:
  - Home: index.md
  - Usage:
      - Turning: 02-Usage/00-usage.md
      - The nine routes: 02-Usage/01-routes.md
      - 360 degree rotation: 02-Usage/02-rotation.md
      - VLM arts: 02-Usage/03-vlm.md
      - Theoretic arts: 02-Usage/04-theoretic.md
  - Theory:
      - Simple Gaze: 01-Theory/00-SimpleGaze.md
      - Simple Head: 01-Theory/01-SImpleHead.md
      - How To Turn: 01-Theory/02-HowToTurn.md
      - Look Anywhere: 01-Theory/03-LookAnywhere.md
      - "It's Alive": 01-Theory/04-It's_Alive.md
  - Tips: 09-Tips/quoets.md
  - TODO: 10-TODO/01-2Sides3dRendering.md
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
